baseURL: ""
title: Francesco Tognetti
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Interests
          url: interests/
          weight: 3
        - name: Focaccias
          url: focaccias/
          weight: 4 

params:
    description: "This website hosts Francesco Tognetti's research papers, curriculum vitae, contact information and a list of Focaccias"
    author: Francesco Tognetti
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "Jan 2, 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: false
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","interests","focaccias"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Francesco Tognetti
          subtitle: "PhD student in mathematical logic at the university of luxembourg"
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Interests
              url: interests/
            - name: Focaccias
              url: focaccias/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:francesco.tognetti@uni.lu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/ftognetti

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Francesco Tognetti"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2